# Directory where data is found
data_dir: ""

# fastq file suffices
fastq1_suffix: "R1_001.fastq.gz"
fastq2_suffix: "R2_001.fastq.gz"

# Directory where analysis is done
analysis_dir: "analysis/"

# Log dir
log_dir: "analysis/log/"

# Container images
container_dir: "containers/"

star_image: "star.sif"
star_container_url: "docker://muabnessor/star:0.1.0"

preprocess_image: "preprocess.sif"
preprocess_container_url: "docker://muabnessor/preprocess:0.1.1"

# reference files
reference_dir: "references/"

genome_file: "Homo_sapiens.GRCh38.dna.primary_assembly.fa"
genome_url: "ftp://ftp.ensembl.org/pub/release-99/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz"

transcripts_file: "Homo_sapiens.GRCh38.99.gtf"
transcripts_url: "ftp://ftp.ensembl.org/pub/release-99/gtf/homo_sapiens/Homo_sapiens.GRCh38.99.gtf.gz"

# rule star_index
read_length: 150
star_index_threads: 16

# Trimming
pre_trim_fastq: False
fastq1_suffix_trimmed: "R1_001_val_1.fq.gz"
fastq2_suffix_trimmed: "R2_001_val_2.fq.gz"

# Align
star_align_threads: 8
